pipeline {
    agent any
    parameters {
        choice choices: ['node-1', 'node-2'], name: 'Name'
    }    
    stages {
        stage('Gits') {
            steps {
                sh 'cd /home/jenkins/iac && git pull'
            }
        }
        stage('Choose node') {
            steps {
                script {
                    if (env.name == 'node-1') {
                        echo 'true'
                        
                    } else {
                        echo 'false'
                    }
                }
            }
        }
        stage('Ansible-playbook'){
            steps{
                ansiblePlaybook disableHostKeyChecking: true, installation: 'ansible', 
                inventory: '/home/jenkins/iac/project/tests/inventory', 
                playbook: '/home/jenkins/iac/playbook/test.yml'
            }
        }
    }
}
