pipeline{
    agent any
    stages{
        stage("clone project"){
            steps{
                sh "cd /home/jenkins/iac && git pull"
            }
        }
        stage("show inventory"){
            steps{
                ansiblePlaybook disableHostKeyChecking: true, installation: 'ansible', 
                inventory: '/home/jenkins/iac/project/tests/inventory', 
                playbook: '/home/jenkins/iac/playbook/test.yml' 
            }
        }
    }
    parameters{
        string defaultValue: 'dat-1' , description: 'choose name' , name: 'name'
    }
    stages{
        stage("demo"){
            steps{
                echo "xin chao ${name}"
            }
        }
    }
}