pipeline{
    agent any
    parameters{
        string defaultValue: 'dat-1' , description: 'choose name' , name: 'name'
        string defaultValue: 'dat-2' , description: 'choose name' , name: 'name'
    }
    stages{
        stage("demo"){
            steps{
                echo "xin chao ${name}"
            }
        }
    }
}